activate_key: default
amp: true
anomaly_clean: true
batch_size: 128
cuda: true
data_type: molecule
drop_out: 0.2
epochs: 50
learning_rate: 0.0001
logger_level: 1
loss_key: default
lr_type: linear
max_epochs: 100
max_norm: 5.0
metrics: r2
model_name: SAT_OLED_Model
num_classes: 3
optim_type: AdamW
patience: 20
pre_norm: true
remove_hs: false
repeat: 1
seed: 42
split: random_5fold
split_method: 5fold_random
split_seed: 42
target_col_prefix: TARGET
target_cols: TARGET0,TARGET1,TARGET2
target_normalize: auto
task: multilabel_regression
warmup_ratio: 0.03
